created data models
johnswyoon/fridgebuddy pull request #7
Opened 2023-07-05 19:33 UTC by JacobRintjema

2023-07-05 20:51 UTC, johnswyoon requested changes
Just added a few comments

2023-07-05 20:51 UTC, johnswyoon commented on backend/models/user-model.ts
> +  dietPreferences : string;
I think we may want an array of strings `dietPreferences: Array<String>`
For example, if someone needs vegan and halal dietary options.

2023-07-05 20:51 UTC, johnswyoon commented on backend/models/recipe-model.ts
> +  recipeIngredients: Array<string>;
According to the Edamam API i think the ingredients are an array of objects
![Screenshot 2023-07-05 at 4 49 58 PM](https://github.com/johnswyoon/fridgebuddy/assets/55363559/9ad7e076-6e7a-4359-b41e-a3c79ca6aa1b)

2023-07-05 20:51 UTC, johnswyoon commented on backend/models/recipe-model.ts
Can you add a field for `images` so we can add a thumbnail in the frontend <3

2023-07-05 20:51 UTC, johnswyoon commented on backend/models/fridge-model.ts
Should we add a "createdOn" date so we can sort by that? Maybe for fridge and items?

2023-07-06 01:49 UTC, JacobRintjema commented on backend/models/user-model.ts
> +  dietPreferences : string;
good point

2023-07-06 01:49 UTC, JacobRintjema commented on backend/models/recipe-model.ts
> +  recipeIngredients: Array<string>;
ty

2023-07-06 01:49 UTC, JacobRintjema commented on backend/models/recipe-model.ts
what data type? how would that work?

2023-07-06 01:50 UTC, JacobRintjema commented on backend/models/fridge-model.ts
you mean in addition to the expirationDate in Item-model?

2023-07-06 04:14 UTC, merged